TERMINOS Y CONDICIONES DE SITIO
Última actualización: 9 de Nobiembre de 2019
Los presentes términos y condiciones (los “Términos y Condiciones”) aplican a todos las Personas (cada uno, un “Usuario”) mayores de edad que accedan al sitio web www.eago.com.mx (el “Sitio” o “Escudería Ago”) y utilicen los servicios ofrecidos en el Sitio y puestos a disposición por Escudería AGO de México, S.A. de C.V. (“LA EMPRESA”), sociedad constituida conforme a las leyes de los Estados Unidos Mexicanos.

1. RELACIÓN CONTRACTUAL.
Usted debe leer cuidadosamente los Términos y Condiciones antes de ingresar o usar el Sitio, debido a que por el simple hecho de usar el Sitio se entenderá que el Usuario ha leído, entendido, aceptado y está de acuerdo en obligarse de conformidad con los Términos y Condiciones, según los mismos sean modificados por LA EMPRESA de tiempo en tiempo. Las modificaciones surtirán efectos una vez que sean publicadas por LA EMPRESA en esta sección del Sitio, por lo que el uso del Sitio y/o sus servicios constituye su consentimiento para obligarse a dichas modificaciones.

El Usuario asegura que la información que ha proporcionado a Escudería Ago es verdadera y completa. LA EMPRESA tendrá derecho, en todo momento, a comprobar dicha información.

2. SERVICIOS.
Los servicios se encuentran dentro del Sitio a disposición de los Usuarios bajo el rubro “CONOCE NUESTROS SERVICIOS”. Los servicios son ADMINISTRACIÓN DE FLOTILLAS, GESTORÍA, TRASLADOS, MECÁNICA, ESTÉTICA y SUBASTAS ELECTRÓNICAS (los “Servicios”). Al acceder a cada Servicio en lo individual, el Usuario podrá encontrar la descripción, alcance, requisitos, contratación y demás elementos propios de cada Servicio, incluyendo los términos y condiciones especiales de dicho Servicio.

Términos y Condiciones Especiales. Los Servicios pueden contener términos y condiciones especiales (los “Términos y Condiciones Especiales”). Al acceder a cada Servicio en lo individual, podrá encontrar los Términos y Condiciones Especiales aplicables a ese Servicio. Los Términos y Condiciones Especiales forman parte de los presentes Términos y Condiciones, por lo que el Usuario debe leer bien los Términos y Condiciones Especiales antes de entrar a contratar cada Servicio.

El Usuario podrá contratar los Servicios a través del Sitio. Para contratar alguno de los Servicios, se debe acceder al Servicio individual y ahí seguir las indicaciones establecidas.

Servicios Adicionales. Escudería Ago podrá ofrecer servicios adicionales que estén relacionados con los Servicios, cuya descripción, requisitos, alcances y costos se encontrarán disponibles en el Sitio para todos los Usuarios. LA EMPRESA se reserva el derecho para otorgar, de tiempo en tiempo, promociones y bonificaciones relacionadas con los Servicios, cuyas características se establecerán en el Sitio. Tanto los servicios adicionales como las promociones y bonificaciones que en su caso existan, podrán estar sujetos a condiciones particulares que podrán diferir total o parcialmente de los presentes Términos y Condiciones (las "Condiciones Particulares"). Consiguientemente, cuando sea aplicable, el Usuario deberá también leer con cuidado las correspondientes Condiciones Particulares antes de acceder a cualesquiera de los Servicios adicionales.

3. USO Y RESTRICCIONES.
Al acceder al Sitio, el Usuario podrá utilizar los Servicios y contenidos del Sitio. Por el simple uso del Sitio, el Usuario otorga su consentimiento pleno para vincularse jurídicamente por los presentes Términos y Condiciones que establecen una relación contractual entre usted y LA EMPRESA. El uso de los Servicios en Escudería Ago es responsabilidad exclusiva del Usuario, quien en todo momento deberá utilizarlos de conformidad con las funcionalidades que se ofrecen y permiten en el Sitio y con los usos autorizados en los presentes Términos y Condiciones. En este sentido, el Usuario se obliga a utilizar el Sitio y los Servicios, de modo tal que no atenten contra las leyes de los Estados Unidos Mexicanos y/o las buenas costumbres, la dignidad de la persona y los derechos de terceros. Los Servicios se ofrecen para ser utilizados de manera personal, privada y particular por el Usuario, por lo que no podrá de manera alguna, ser copiado, modificado, dado en licencia o cesión de derechos, publicado, reproducido o utilizado con fines comerciales. Queda expresamente prohibido el uso o aplicación de cualesquiera recursos técnicos, lógicos o tecnológicos por virtud de los cuales los Usuarios puedan beneficiarse, directa o indirectamente, con o sin lucro, de la explotación no autorizada de los Servicios y/o contenidos del Sitio. LA EMPRESA tendrá, en todo momento, el derecho de negar, restringir, suspender, cancelar o condicionar al Usuario el acceso al y/o uso de los Servicios, ya sea total o parcialmente, de manera temporal o definitiva y sin necesidad de previo aviso, si el Usuario incumple cualquiera de las estipulaciones de los presentes Términos y Condiciones o si no pudiera verificarse su identidad o si cualquier información proporcionada por el mismo fuere falsa, sin responsabilidad para LA EMPRESA. LA EMPRESA tendrá el derecho de modificar los Servicios y/o contenidos del Sitio, sin que lo anterior se considere un incumplimiento de LA EMPRESA. El Usuario acepta que el uso de algunos de los Servicios puede requerir de un registro previo, así como de cualquier otro requisito que establezca LA EMPRESA en los Términos y Condiciones Especiales del Servicio que se trate y/o en el Sitio.

4. LÍMITES O EXCLUYENTES DE RESPONSABILIDAD.
LA EMPRESA no será responsable por los daños derivados del uso de o incapacidad de usar los medios de comunicación electrónicos con el Sitio, incluyendo sin limitar, los daños derivados del fallo o retraso en la entrega de comunicaciones electrónicas, intercepción o manipulación de comunicaciones electrónicas por terceros o por programas informáticos usados para comunicaciones electrónicas y transmisión de virus. El Usuario acepta expresamente que LA EMPRESA no será responsable por cualquier daño, perjuicio o pérdida que surja en relación con fallas en el rendimiento, error, omisión, interrupción, defecto, demora en la operación o transmisión del Sitio, o en la Internet, ni por cualquier virus de computadora o falla de Sitio o línea que pudiera infectar o afectar el equipo del Usuario como consecuencia del acceso o uso del Sitio o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo; así como tampoco LA EMPRESA será responsable de los daños o perjuicios que se ocasionen como consecuencia de deficiencias, desperfectos, fallas u otros problemas que se originen por la instalación, adecuación y conexión de sitios del Usuario, ni de los daños y perjuicios que se le pudieran causar si, por caso fortuito, fuerza mayor o por cualquier otro acontecimiento o circunstancia inevitable, más allá del control razonable de LA EMPRESA, el Usuario no pudiera hacer uso o uso oportuno del Sitio. LA EMPRESA no asume ninguna especie de responsabilidad que se derive de cualquier daño o perjuicio, directo o indirecto, generado o de cualquier forma relacionado con el acceso o utilización de este Sitio (aun cuando LA EMPRESA haya tenido conocimiento de la posibilidad del daño), incluyendo la responsabilidad relacionada con daños ocasionados por virus o malware que infecten el/los Sitio(s) de cómputo del Usuario. Tampoco será responsable LA EMPRESA en caso de que existan problemas de conexión o fallan en los sistemas bancarios y por ello, no se pueda realizar algún pago del Servicio contratado, y por tanto no se pueda llevar a cabo el Servicio.

5. CONTENIDOS DEL SITIO.
La información contenida en el Sitio ha sido incluida y/o elaborada por LA EMPRESA con la finalidad de proporcionar información general a los Usuarios. LA EMPRESA se reserva el derecho de actualizar, cambiar, modificar o eliminar la información incluida en el Sitio, en cualquier momento y sin previo aviso. La información que LA EMPRESA pone a disposición de los Usuarios a través del Sitio, es de naturaleza general y ha sido obtenida de fuentes que se consideran fidedignas; sin embargo, LA EMPRESA no garantiza su veracidad. La intención de proporcionar esta información y opiniones en el Sitio, son meramente enunciativas y deberán ser consideradas por el Usuario exclusivamente para efectos informativos, por lo que su utilización será bajo la más estricta responsabilidad exclusiva del Usuario. LA EMPRESA no será responsable de cualquier daño o perjuicio que sufra el Usuario como consecuencia de demoras, inexactitudes, errores u omisiones de cualquier índole, cambios o mejoras que se realicen periódicamente a los contenidos, ni tampoco de los resultados obtenidos por la utilización de la información contenida en el Sitio o por el uso del Sitio o de los servicios.

6. CUENTA DEL USUARIO Y CLAVES DE ACCESO
En caso de que en el Sitio se requiera de algún registro previo para usar algún Servicio, el Usuario recibirá un nombre de usuario y una contraseña (las “Claves de Acceso”). El Usuario será responsable de todas las actividades que se realicen bajo su Clave de Acceso o en su cuenta. Usted acepta (a) notificar de inmediato a LA EMPRESA cualquier uso no autorizado de su Clave de Acceso o cuenta; o bien, cualquier otra violación a la seguridad; y (b) asegurarse de salir de su cuenta al finalizar cada sesión. Las Claves de Acceso son personales, confidenciales e intransferibles por lo que, en todo momento, la custodia y el uso de dichas Claves de Acceso, serán de la exclusiva responsabilidad del Usuario. LA EMPRESA no será responsable de ninguna pérdida o daño que surja de su incumplimiento con este apartado. En los Servicios que no se requiera registro alguno, el Sitio podrá solicitar algunos datos al Usuario relativos al tipo de Servicio que se pretenda usar.

7. CONFIDENCIALIDAD
LA EMPRESA se obliga a mantener como confidencial, la información que reciba del Usuario que tenga dicho carácter de conformidad con las disposiciones legales aplicables en los Estados Unidos Mexicanos y sujeto a los términos del Aviso de Privacidad de LA EMPRESA. El Usuario reconoce y acepta que LA EMPRESA no será responsable de mantener con el carácter de confidencial, cualquier otra información que el Usuario libremente le proporcione, ya sea al registrase en el Sitio o en cualquier otro momento posterior, que sea de cualquier forma pública o que no deba considerarse como confidencial en términos de las disposiciones legales aplicables, incluyendo aquella información que el Usuario proporcione a través de comunicados o plática en línea (chats), así como la información que obtenga LA EMPRESA a través de las Cookies.

El contenido del Sitio puede imprimirse, descargarse y recibir un nuevo formato solo para uso personal y no comercial. El contenido del Sitio, en todo o en parte, no debe utilizarse ni explotarse de ninguna forma con fines comerciales, incluidos la descarga, la copia, la duplicación, la vinculación, la muestra, la distribución o la reproducción, sin el consentimiento expreso escrito de LA EMPRESA. Usted acepta no utilizar el contenido del Sitio con propósitos comerciales o ilegales y acepta no manipular, eliminar, ocultar, quitar, agregar o de alguna otra manera modificar dicho contenido; o bien, permitir o ayudar a que otros lo hagan.

8. TRATAMIENTO DE DATOS PERSONALES
Para mayor información sobre el tratamiento de los datos personales de los Usuarios del Sitio, favor de dirigirse al Aviso de Privacidad de LA EMPRESA disponible en el mismo Sitio de Escudería Ago.

9. COOKIES
El Usuario que tenga acceso al Sitio, está de acuerdo en recibir las Cookies que les transmitan los servidores. Una "Cookie" es un archivo de datos que se almacena en el disco duro de la computadora del Usuario cuando éste tiene acceso al Sitio. Las Cookies pueden contener información tal como la identificación proporcionada por el Usuario o información para rastrear las páginas que el Usuario ha visitado.

10. SERVICIOS DE TERCEROS
El Usuario acepta que dentro del Sitio podrán existir ligas o vínculos a otras páginas web propiedad de terceras personas y ajenas a LA EMPRESA. Si el Usuario decide ingresar a dichas páginas externas, será responsabilidad exclusiva del Usuario cualquier actividad e interacción que ahí lleve a cabo. LA EMPRESA no será responsable de forma alguna de la participación y actividad que tenga el Usuario en las páginas web externas al Sitio ni tampoco del contenido de dichas páginas.

11. PROHIBICIONES
El Usuario se compromete a no utilizar el Sitio para la realización de actividades contrarias a la Ley, a la moral, a las buenas costumbres aceptadas o al orden público establecido, incluyendo sin limitar actividades con fines o efectos ilícitos, prohibidos o lesivos de derechos e intereses de terceros, liberando a LA EMPRESA de cualquier responsabilidad que se pudiera derivar de todo lo anterior. Los Usuarios no podrán utilizar el Sitio de modo que interfiera, impida o limite el normal y correcto uso y disfrute de cualquier otro Usuario o de LA EMPRESA. El Usuario reconoce que no tiene el derecho de y, por lo tanto, acepta y se obliga a no colocar hiperligas de y al Sitio, ni a colocar o utilizar los servicios y/o contenidos del Sitio en páginas propias o de terceros sin autorización previa y por escrito de LA EMPRESA. El Usuario no podrá ceder ni transferir, de forma alguna, los derechos que adquiera al contratar el Servicio.

12. VIOLACIÓN A ESTOS TÉRMINOS Y CONDICIONES
LA EMPRESA se reserva el derecho de llevar a cabo todas las acciones legales que sean necesarias para remediar cualquier violación a los presentes Términos y Condiciones, incluso el de restringir el acceso al Sitio y los servicios a Usuarios.

13. PROPIEDAD INTELECTUAL
Los derechos de propiedad industrial o intelectual, incluyendo sin limitar el contenido, así como las marcas, diseños, avisos comerciales, signos distintivos, nombres comerciales, diseños industriales y dominios exhibidos en y/o que se desprendan del Sitio y/o los Servicios, así como los derechos de uso y explotación de los mismos, incluyendo sin limitar su divulgación, publicación, reproducción, distribución y transformación, son propiedad exclusiva de LA EMPRESA o del legítimo titular de los mismos y están protegidos por las leyes y tratados internacionales aplicables. El Usuario no adquiere ni podrá adquirir ningún derecho de propiedad industrial o intelectual por el simple uso del Sitio y servicios y, en ningún momento, dicho uso será considerado como una autorización ni licencia para utilizar los servicios y contenidos del Sitio con fines distintos a los que se contemplan en los presentes Términos y Condiciones.

14. MODIFICACIONES
Al acceder al Sitio, el Usuario entiende y acepta que LA EMPRESA tendrá, en todo momento, el derecho de modificar, los presentes Términos y Condiciones, sin previo aviso. En consecuencia, el Usuario acepta que es su obligación el revisar periódicamente estos Términos y Condiciones y leerlos cada vez que pretenda usar el Sitio y los servicios.

15. LEYES APLICABLES Y JURISDICCIÓN
Para la interpretación, cumplimiento y ejecución de los presentes Términos y Condiciones, las partes están de acuerdo en que serán aplicables las leyes federales de los Estados Unidos Mexicanos y competentes los tribunales ubicados en la Ciudad de México, renunciando expresamente a cualquier otro fuero o jurisdicción que pudiera corresponderles en razón de sus domicilios presentes o futuros o por cualquier otra causa.
